spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

    username: questify
    password: questify-postgreql
  jpa:
    hibernate:

      ddl-auto: create-drop
    generate-ddl : true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: questify_jwt_token_naja_don't_peak_na