spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

    username: questify
    password: questify-postgreql
  jpa:
    hibernate:

      ddl-auto: create-drop
    generate-ddl : true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect